### ISSUE TITLE
Use berglas for securely retrieving vault host and token

### ISSUE THREAD

**Issue by stevenaldinger** [nytimes/gcp-vault#15]
Passing in the vault host/token in environment variables show in plain text in the GCP console (for cloud functions at least, I think this is true across all their products though).

It looks like there are other ways to pass in the config outside of environment variables, but have you all considered including [berglas](https://github.com/GoogleCloudPlatform/berglas) and using Google KMS + a GCS bucket for storing the encrypted host/token? It allows for easy rotation of the auth token and avoids insecure environment variables.

I tried checking out the cloud function example to see how you were handling that but I'm pretty new to golang and struggled to tell how you were dealing with it, it looked like env vars though.

I have an example of how to handle Vault with berglas in cloud functions if you haven't already decided against it, I'd be happy to share some code.

Thanks!

**Comment by stevenaldinger** [comment]
I think it'd be neat if this was actually built into the gcp-vault code but I threw it into the GCF example to demonstrate how it could be used.

**Comment by jprobinson** [comment]
Howdy @stevenaldinger, thanks for your interest in the project!

When using gcp-vault within GCF or GAE, we actually don't recommend users inject the access token as, just like you say, it is exposed in plain text within the GCP console.

Instead, we recommend devs use the [Vault GCP IAM login method](https://www.vaultproject.io/docs/auth/gcp.html#iam-login) along with gcp-vault via the [Config struct's "Role" field](https://github.com/nytimes/gcp-vault/blob/master/gcpvault.go#L26-L30).

For more information about how we use this tool at NYT, I have a somewhat recent talk available: https://www.hashicorp.com/resources/using-hashicorp-vault-google-serverless

This still leaves the host name in plain text, but that is certainly much better than the token itself. If you feel the hostname should still be encrypted somehow, I wouldn't be totally against adding some additional/optional config fields that would encrypt the hostname with KMS/Berglas directly. I'm just a little wary of adding more moving parts to this critical startup path, which is why I'd probably vote for making such an addition as optional.

**Comment by stevenaldinger** [comment]
Thanks for the thoughtful response and the addition resources! I will definitely check out your talk later today.
